from __future__ import annotations

V2_BODY_FIELDS: dict[str, tuple[str, ...]] = {
    "put-assets-edit-id": (
        "BusinessUnits",
        "name",
        "description",
        "GrcContacts",
        "AssetOwners",
        "AssetGuardians",
        "AssetUsers",
        "AssetLabels",
        "AssetMediaTypes",
        "RelatedAssets",
        "Legals",
        "review",
        "Processes",
    ),
    "put-settings-authentication": (
        "connection_type",
        "ldap_connector_id",
        "oauth_connector_id",
        "saml_connector_id",
        "auth_policies",
        "auth_awareness",
        "auth_account_review",
        "auth_vendor_assessment",
    ),
    "put-authorizations-update": ("authorization", "group_id", "permission", "action"),
    "put-authorizations-update-bulk": ("authorizations", "group_id", "permission"),
    "put-goals-edit-id": (
        "name",
        "description",
        "Owners",
        "Contacts",
        "status",
        "audit_calendar_type",
        "audit_calendar_mode",
        "audit_periodical",
        "audit_specific",
        "audit_metric_description",
        "audit_success_criteria",
        "AuditOwners",
        "AuditEvidenceOwners",
        "SecurityPolicies",
        "SecurityServices",
        "Risks",
        "ThirdPartyRisks",
        "BusinessContinuities",
        "Projects",
        "ProgramIssues",
    ),
    "get-settings-test-mail-connection": (
        "test_email",
        "SMTP_USE",
        "EMAIL_NAME",
        "NO_REPLY_EMAIL",
        "QUEUE_TRANSPORT_LIMIT",
    ),
    "get-settings-deactivate-license": ("client_key",),
    "get-settings-activate-license": ("client_key",),
    "get-settings-test-public-address": ("PUBLIC_ADDRESS",),
    "post-settings-reset-database": ("reset_db",),
    "post-settings-reset-application-id": ("reset_app_id",),
    "post-settings-remove-legacy-views": ("remove_legacy_views",),
    "post-settings-flush-emails-in-queue": (),
    "put-visualisation-settings-edit-status-id": ("status",),
    "put-app-notifications-id-view": (),
    "get-custom-dynamic-status-custom-dynamic-statuses-edit-status-enabled-id": ("enabled",),
    "put-custom-dynamic-status-custom-dynamic-statuses-edit-status-visible-id": ("visible",),
    "put-filters-id": ("filter", "view", "update"),
    "delete-filters-id": (),
    "post-filters": ("name", "model", "params"),
    "put-filters-id-share": ("view", "update", "options"),
    "put-filters-id-pin": ("pinned",),
    "put-filters-id-default": ("default",),
    "put-filters-id-params": ("params",),
    "put-filters-id-default-for-all": ("default_for_all",),
    "put-customization-customization-model-alias": ("elements",),
    "post-customization-customization-reset-model-alias": (),
    "put-notifications-notification-system-items-edit-status-id": ("status",),
    "get-translations-translations-edit-status-id": ("status",),
    "post-triggers-triggers-test-trigger-model": (
        "global",
        "runtime",
        "name",
        "language",
        "timeout",
        "composer_packages",
        "code",
    ),
    "post-triggers-triggers-test-trigger-formatting-model": (
        "global",
        "runtime",
        "name",
        "language",
        "timeout",
        "composer_packages",
        "code",
    ),
    "post-triggers-triggers-test-trigger-validate-model": (
        "global",
        "runtime",
        "name",
        "language",
        "timeout",
        "composer_packages",
        "code",
    ),
}

V2_RAW_STRING_FIELDS: dict[str, tuple[str, ...]] = {
    "post-filters": ("params",),
    "put-filters-id-params": ("params",),
}

V2_DATA_WRAPPED_ACTIONS = frozenset(
    {
        "put-assets-edit-id",
        "put-goals-edit-id",
    }
)
